---
# SPDX-FileCopyrightText: 2023 CERN (home.cern)
#
# SPDX-License-Identifier: BSD-3-Clause

# Projects to include in the OHWR website.
projects:
    # Unique project identifier.
    # The project page URL depends on the id (i.e. http://ohwr.org/projects/<id>/).
  - id: 'svec'
    # URL to the Git repository of the project.
    # The Git repository must contain a .ohwr.yaml file.
    url: 'https://github.com/vascoguita/svec.git'
  - id: 'spec'
    url: 'https://github.com/vascoguita/spec.git'
  - id: 'fmc-tdc'
    url: 'https://github.com/vascoguita/fmc-tdc.git'
  - id: 'fmc-delay-1ns-8cha'
    url: 'https://github.com/vascoguita/fmc-delay-1ns-8cha.git'
  - id: 'fmc-adc-100m14b4cha'
    url: 'https://github.com/vascoguita/fmc-adc-100m14b4cha.git'
