---
# SPDX-FileCopyrightText: 2024 CERN (home.cern)
#
# SPDX-License-Identifier: BSD-3-Clause

sources: './src/hugo'

licenses: './third_party/spdx/license-list-data/json/licenses.json'

categories:
  - name: 'FMC Carriers'
    description: 'Boards that connect FMC Modules'
  - name: 'FMC Modules'
    description: 'FPGA Mezzanine Cards'

projects:
  - id: 'svec'
    repository: 'https://github.com/vascoguita/svec.git'
    contact:
      name: 'Vasco Guita'
      email: 'vasco.guita@cern.ch'
    featured: true
    categories:
      - 'FMC Carriers'
  - id: 'spec'
    repository: 'https://github.com/vascoguita/spec.git'
    contact:
      name: 'Vasco Guita'
      email: 'vasco.guita@cern.ch'
    featured: true
    categories:
      - 'FMC Carriers'
  - id: 'fmc-tdc'
    repository: 'https://github.com/vascoguita/fmc-tdc.git'
    contact:
      name: 'Vasco Guita'
      email: 'vasco.guita@cern.ch'
    categories:
      - 'FMC Modules'
    parents:
      - 'spec'
      - 'svec'
  - id: 'fmc-delay-1ns-8cha'
    repository: 'https://github.com/vascoguita/fmc-delay-1ns-8cha.git'
    contact:
      name: 'Vasco Guita'
      email: 'vasco.guita@cern.ch'
    categories:
      - 'FMC Modules'
    parents:
      - 'spec'
      - 'svec'
  - id: 'fmc-adc-100m14b4cha'
    repository: 'https://github.com/vascoguita/fmc-adc-100m14b4cha.git'
    contact:
      name: 'Vasco Guita'
      email: 'vasco.guita@cern.ch'
    categories:
      - 'FMC Modules'
    parents:
      - 'spec'
      - 'svec'
