---
# SPDX-FileCopyrightText: 2023 CERN (home.cern)
#
# SPDX-License-Identifier: BSD-3-Clause

# Logging level ('DEBUG', 'INFO', 'WARNING', 'ERROR' or 'CRITICAL')
log_level: 'INFO'

# Hugo sources directory
source: './src/hugo'

# Projects to include in the OHWR website.
projects:
    # Unique project identifier.
    # The project page URL depends on the id (i.e. http://ohwr.org/projects/<id>/).
  - id: 'svec'
    # URL to the Git repository of the project.
    # The Git repository must contain a .ohwr.yaml file.
    url: 'https://github.com/vascoguita/svec.git'
    # (optional) Project type ('regular' or 'featured').
    # The OHWR highlights featured projects.
    type: 'featured'
  - id: 'spec'
    url: 'https://github.com/vascoguita/spec.git'
    type: 'featured'
  - id: 'fmc-tdc'
    url: 'https://github.com/vascoguita/fmc-tdc.git'
  - id: 'fmc-delay-1ns-8cha'
    url: 'https://github.com/vascoguita/fmc-delay-1ns-8cha.git'
  - id: 'fmc-adc-100m14b4cha'
    url: 'https://github.com/vascoguita/fmc-adc-100m14b4cha.git'
