# SPDX-FileCopyrightText: 2024 CERN (home.cern)
#
# SPDX-License-Identifier: BSD-3-Clause

version = 1
SPDX-PackageName = "ohwr.org"
SPDX-PackageSupplier = "CERN (home.cern)"
SPDX-PackageDownloadLocation = "https://github.com/OHWR/ohwr.org"

[[annotations]]
path = "src/hugo/go.sum"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 CERN (home.cern)"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "third_party/spdx/license-list-data/json/licenses.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 CERN (home.cern)"
SPDX-License-Identifier = "CC-BY-SA-4.0+"
