---
# SPDX-FileCopyrightText: 2025 CERN (home.cern)
#
# SPDX-License-Identifier: BSD-3-Clause

name: Build

permissions:
  contents: read

on:  # yamllint disable-line rule:truthy
  workflow_call:
    outputs:
      error:
        value: ${{ jobs.build.outputs.error }}
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      error: ${{ steps.build.outputs.error }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.147.2'
          extended: true
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12.3'
      - name: Install dependencies
        run: |
          pip install pydantic PyYAML email_validator requests \
          -c requirements.txt
      - name: Build
        id: build
        run: |
          echo "error<<EOF" >> "$GITHUB_OUTPUT"
          make build 2>&1 | \
            tee >(grep -oP ' - ERROR - \K.*(?=:)' >> "$GITHUB_OUTPUT")
          echo "EOF" >> "$GITHUB_OUTPUT"
        env:
          HUGO_BASEURL: "${{ steps.pages.outputs.base_url }}/"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./public
