---
# SPDX-FileCopyrightText: 2024 CERN (home.cern)
#
# SPDX-License-Identifier: BSD-3-Clause

name: Deploy to GitHub Pages

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: '0 8,15 * * *'
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/build.yaml
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  notify:
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.outputs.error != ''
    steps:
      - name: Notify Mattermost Channel
        uses: mattermost/action-mattermost-notify@2.0.0
        with:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          # yamllint disable rule:line-length
          TEXT: |
            Some errors occured while building the ohwr.org website:
            ```
            ${{ needs.build.outputs.error }}
            ```
            Please check the [pipeline logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.
